apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplewebapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simplewebapp
  template:
    metadata:
      labels:
        app: simplewebapp
    spec:
      containers:
      - name: simplewebapp
        image: stark303/simplewebapp:latest
        ports:
        - containerPort: 80  # Expose HTTP port for your app
