apiVersion: v1
kind: Service
metadata:
  name: simplewebapp-service
spec:
  selector:
    app: simplewebapp  # This matches the label in the deployment
  ports:
    - protocol: TCP
      port: 80           # The internal port for HTTP communication
      targetPort: 80      # The port the container is listening on
      nodePort: 30080     # The port on your EC2 instance to access the service externally
  type: NodePort         # Exposes the service on a high port on each node
